#db.properties
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

decorator.datasource.p6spy.enable-logging=true
logging.level.org.hibernate.SQL=debug

server.servlet.context-path=/
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB
spring.servlet.multipart.location=/tmp
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.thymeleaf.cache=false

spring.jpa.open-in-view=true

# default image value
tmpFile.dir = /image/tmp/
file.dir = /image/default/
default.profile=default_profile.jpg
default.background=default_bg.jpg
default.weekly=weekly_default_thumbnail.png


# google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=${GOOGLE_CLIENT_SCOPE}